# Generated by Django 4.2.3 on 2023-07-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0002_dersler_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_metni', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='dersler.dersler')),
                ('yorum_yapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dersler.dersler')),
            ],
        ),
    ]
