# Generated by Django 4.2.3 on 2023-07-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0003_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersler',
            name='begeni_sayisi',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
