# Generated by Django 4.2.3 on 2023-07-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0007_kullanicibegeni_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersler',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
