# Generated by Django 4.2.3 on 2023-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0009_remove_dersler_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersler',
            name='kategori',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
